-- Customer
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('1', 'Mr.', 'FIRST_NAME1', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('2', 'Mr.', 'FIRST_NAME2', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('3', 'Mr.', 'FIRST_NAME3', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('4', 'Mr.', 'FIRST_NAME4', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('5', 'Mr.', 'FIRST_NAME5', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('6', 'Mr.', 'FIRST_NAME6', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('7', 'Mr.', 'FIRST_NAME7', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('8', 'Mr.', 'FIRST_NAME8', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('9', 'Mr.', 'FIRST_NAME9', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('10', 'Mr.', 'FIRST_NAME10', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('11', 'Mr.', 'FIRST_NAME11', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('12', 'Mr.', 'FIRST_NAME12', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('13', 'Mr.', 'FIRST_NAME13', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('14', 'Mr.', 'FIRST_NAME14', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('15', 'Mr.', 'FIRST_NAME15', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('16', 'Mr.', 'FIRST_NAME16', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('17', 'Mr.', 'FIRST_NAME17', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('18', 'Mr.', 'FIRST_NAME18', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('19', 'Mr.', 'FIRST_NAME19', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);
INSERT INTO CUSTOMER(ID, SALUTATION, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('20', 'Mr.', 'FIRST_NAME20', 'LAST_NAME1', SYSDATE, SYSDATE, SYSDATE, 1);

-- Address
INSERT INTO ADDRESS(ID, ADDRESS_TYPE, ADDRESS1, ADDRESS2, CITY, STATE, COUNTRY, ZIPCODE, CUSTOMER_ID, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('1', 'RESIDENCE', 'H.No. 123', 'Kukatpally', 'Hyderabad', 'Telangana', 'India', '500072', '1', SYSDATE, SYSDATE, 1);
INSERT INTO ADDRESS(ID, ADDRESS_TYPE, ADDRESS1, ADDRESS2, CITY, STATE, COUNTRY, ZIPCODE, CUSTOMER_ID, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('2', 'MAILING', 'H.No. 123', 'Kukatpally', 'Hyderabad', 'Telangana', 'India', '500072', '1', SYSDATE, SYSDATE, 1);
INSERT INTO ADDRESS(ID, ADDRESS_TYPE, ADDRESS1, ADDRESS2, CITY, STATE, COUNTRY, ZIPCODE, CUSTOMER_ID, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('3', 'OFFICE', 'Cyber Towers, Hi-Tech City', 'Madhapur', 'Hyderabad', 'Telangana', 'India', '500081', '1', SYSDATE, SYSDATE, 1);
INSERT INTO ADDRESS(ID, ADDRESS_TYPE, ADDRESS1, ADDRESS2, CITY, STATE, COUNTRY, ZIPCODE, CUSTOMER_ID, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('4', 'RESIDENCE', 'H.No. 456', 'Gollapudi', 'Vijayawada', 'Andhra Pradesh', 'India', '521225', '2', SYSDATE, SYSDATE, 1);
INSERT INTO ADDRESS(ID, ADDRESS_TYPE, ADDRESS1, ADDRESS2, CITY, STATE, COUNTRY, ZIPCODE, CUSTOMER_ID, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('5', 'MAILING', 'Hi-Tech estates', 'Patamata', 'Vijayawada', 'Andhra Pradesh', 'India', '520010', '3', SYSDATE, SYSDATE, 1);
INSERT INTO ADDRESS(ID, ADDRESS_TYPE, ADDRESS1, ADDRESS2, CITY, STATE, COUNTRY, ZIPCODE, CUSTOMER_ID, CREATED_DATE, MODIFIED_DATE, REVISION) VALUES('6', 'OFFICE', 'Hi-Tech estates', 'Patamata', 'Vijayawada', 'Andhra Pradesh', 'India', '520010', '4', SYSDATE, SYSDATE, 1);